# Numpy

In [1]:
#numpy (numerical python)
#numpy is a linear algebra library for python.the reason it is so important in data science is that almost all of the libraries 
#in Pydata Ecosystem rely on numpy as one of their main bulilding blocks.
#pip install numpy

# Numpy Arrays
#Array is a data structure that stores values of same data type like numbers strings etc.
#numpy arrays come in 2 flavors i.e. vectors and matrices
#vectors are strictly 1-dimensional arrays and matrices are 2-dimensional arrays

# methods for numpy array creation

## 1.array()

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
a.shape     #no. of rows = no. of columns hence (4,)

(4,)

In [6]:
b=np.array([4,5,6])
b


array([4, 5, 6])

In [7]:
b.shape

(3,)

In [8]:
c=np.array([[1,2],[3,4]])
c

array([[1, 2],
       [3, 4]])

In [9]:
c.shape

(2, 2)

In [10]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
d.shape

(3, 3)

## ndim =no.of dimensions of array

In [12]:
a

array([1, 2, 3, 4])

In [13]:
a.ndim

1

In [14]:
c

array([[1, 2],
       [3, 4]])

In [15]:
c.ndim

2

In [16]:
d.ndim

2

# 2.Random method for numpy array creation


### 1.randint = it creates array of random integers between low and high value

In [17]:
import random
np.random.randint(50,60,5)

array([57, 55, 52, 55, 55])

In [18]:
np.random.randint(20,100,10)

array([32, 33, 36, 81, 99, 38, 54, 76, 75, 77])

### 2.rand = it creates array of random numbers uniformly distributed between 0 and 1


In [19]:
np.random.rand(5)

array([0.89108128, 0.5771129 , 0.36878019, 0.18064997, 0.15729949])

In [20]:
np.random.rand(7)

array([0.32025731, 0.24156653, 0.2264504 , 0.42337295, 0.80350317,
       0.52952826, 0.4708823 ])

### 3.randn = it creates standard normal distribution around zero (includes -ve values also)¶

In [21]:
np.random.randn(5)

array([ 0.61774388,  0.66301434, -1.31948818,  1.06262169, -0.29643691])

# 3. numpy.arange() Method¶


### syntax = np.arange(start,stop,step,dtype)


In [22]:
#numpy.arange()
#it returns evenly spaced values within a range
#arange methood = this is a comman way of creating numpy arrays
#syntax = np.arange(start,stop,step,dtype)
#step = spacing or difference btn 2 values
import numpy as np
x=np.arange(0,10,2)
x

array([0, 2, 4, 6, 8])

In [23]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [24]:
z=np.arange(9)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
y=np.arange(20,80,5,dtype='float')
y

array([20., 25., 30., 35., 40., 45., 50., 55., 60., 65., 70., 75.])

# 4.numpy.linspace

### syntax =  np.linspace(start,stop,num,dtype)

In [26]:
#numpy.linspace
#4 linspace method
#it is similar to arange function ,instead of step ,number of evenly spaced values between the interval is specified.
#syntax
#np.linspace(start,stop,num,dtype)
#num= no.of evenly spaced values to be generated
a=np.linspace(0,10,5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
a=np.arange(0,10,5)
a

array([0, 5])

In [28]:
a=np.linspace(0,10,5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## reshape

### to change the shape of the array

In [29]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
a.ndim

1

In [32]:
b.ndim

2

In [33]:
z=np.array([0,1,2,3])
z

array([0, 1, 2, 3])

In [34]:
y=z.reshape(2,2)
y

array([[0, 1],
       [2, 3]])

In [35]:
v=np.arange(12).reshape(3,4)
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## np.zeros


### numpy zeros = it returns new array of specified size filled with zeros

In [37]:
np.zeros(2)

array([0., 0.])

In [38]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [39]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## numpy.ones()

In [40]:
np.ones(3)

array([1., 1., 1.])

In [41]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
#identity matrix
#np.eye()
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### indexing and slicing


In [44]:
#basic slicing
import numpy as np
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
x[2:6]

array([2, 3, 4, 5])

In [46]:
x[4:9]

array([4, 5, 6, 7, 8])

In [47]:
x[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [49]:
x[2:7:2]        #2 is step

array([2, 4, 6])

In [50]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
d[1][0]

4

In [52]:
d[1:] #below index 1 in row

array([[4, 5, 6],
       [7, 8, 9]])

In [53]:
d[:2]# 0,1 row

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
d[:2][1:]

array([[4, 5, 6]])

In [59]:
d[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [64]:
d[1:3][0:1]

array([[4, 5, 6]])

In [65]:
b=np.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
b

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [66]:
b.ndim

2

In [67]:
b[1:2][0:2]

array([[20, 25, 30]])

### advanced boolean indexing/conditional indexing


In [68]:
s=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
s

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
s.shape

(4, 3)

In [70]:
s<5

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [71]:
s[s>5]

array([ 6,  7,  8,  9, 10, 11])

### iterating over an array using for loop
### np.nditer()

In [72]:
a=np.arange(0,60,5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [73]:
b=a.reshape(3,4)
b

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [74]:
for i in b:
    for j in i:
        print(j)

0
5
10
15
20
25
30
35
40
45
50
55


In [75]:
np.nditer(b)

In [76]:
for i in np.nditer(b):
    print(i)

0
5
10
15
20
25
30
35
40
45
50
55


# Array Manipulation

### 1.broadcasting

In [77]:
##1.broadcasting
#numpy arrays differ from normal python list beacuse of their ability to broadcast
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
y=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [79]:
#y[1:5]=100
#y

In [80]:
x[1:5]=100
x

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [81]:
#x1[0:6]=100
# list is not capable of broadcasting

In [82]:
x

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [83]:
x[7:]=10
x

array([  0, 100, 100, 100, 100,   5,   6,  10,  10,  10])

In [84]:
x[0:5]=[100,101,102,103,104]
x

array([100, 101, 102, 103, 104,   5,   6,  10,  10,  10])

In [85]:
#2.numpy.concatenate()
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [86]:
b=np.array([[5,6],[7,8]])
b


array([[5, 6],
       [7, 8]])

In [87]:
#axis 0 =row (rowwise)
#axis 1 =column (columnwise)
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [88]:
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [89]:
#3.numpy.transpose
d=np.arange(12).reshape(3,4)
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
np.transpose(d)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [91]:
#4.numpy.split()
v=np.arange(9)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [92]:
# split into 3 equal sized arrays
np.split(v,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [93]:
#split at particular position
np.split(v,[4,7])

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [94]:
## 5.numpy.append()
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
#without axis it will create a 1-dimensional array
np.append(a,[7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
np.append(a,[[7,8,9]],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
np.append(a,[[5,5,5],[7,8,9]],axis=1)

array([[1, 2, 3, 5, 5, 5],
       [4, 5, 6, 7, 8, 9]])

In [100]:
## 6.#numpy.insert()
x=np.array([[1,2],[3,4],[5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [101]:
#without axis it will create a 1-dimensional array
#[1,2,3,4,5,6]=[1,2,3,11,12,4,5,6]
np.insert(x,3,[11,12])

array([ 1,  2,  3, 11, 12,  4,  5,  6])

In [106]:
np.insert(x,1,[11],axis=0)    # row [11,11] is inserted after 1

array([[ 1,  2],
       [11, 11],
       [ 3,  4],
       [ 5,  6]])

In [107]:
np.insert(x,1,[11],axis=1)       # column [11,11] is inserted after 1

array([[ 1, 11,  2],
       [ 3, 11,  4],
       [ 5, 11,  6]])

In [110]:
import numpy as np
np.insert(x,1,[11,12],axis=0)

array([[ 1,  2],
       [11, 12],
       [ 3,  4],
       [ 5,  6]])

## 15-3-2022

In [1]:
#functions for rounding
#1 .numpy.around
import numpy as np
a=np.array([1.0,5.35,123,0.567,25.532])
a

array([  1.   ,   5.35 , 123.   ,   0.567,  25.532])

In [2]:
np.around(a)

array([  1.,   5., 123.,   1.,  26.])

In [3]:
np.around(a,decimals=1)

array([  1. ,   5.4, 123. ,   0.6,  25.5])

In [4]:
from math import *

In [5]:
floor(10.00002)

10

In [6]:
floor(3.26589)

3

In [7]:
ceil(10.00002)

11

In [8]:
#numpy.floor
b=np.array([-1.7,1.5,-0.2,0.6,10,-5.6])
b

array([-1.7,  1.5, -0.2,  0.6, 10. , -5.6])

In [9]:
np.floor(b)

array([-2.,  1., -1.,  0., 10., -6.])

In [10]:
#-ve num then it will take next integer -1.7 = -2
#+ve it will remove the decimal part 1.5 = 1

In [11]:
b=np.array([-10.7,15.5,-5.6,7.6,10,-8.6])
b

array([-10.7,  15.5,  -5.6,   7.6,  10. ,  -8.6])

In [12]:
np.floor(b)

array([-11.,  15.,  -6.,   7.,  10.,  -9.])

In [13]:
#numpy.ceil
#-ve num  it will remove the decimal part -1.7 = -1
#+ve it will taje next integer 1.5 = 2
b

array([-10.7,  15.5,  -5.6,   7.6,  10. ,  -8.6])

In [14]:
np.ceil(b)

array([-10.,  16.,  -5.,   8.,  10.,  -8.])

In [15]:
#arithmatic operations
t1=np.arange(9).reshape(3,3)
t1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
t2=np.array([10,10,10])
t2

array([10, 10, 10])

In [17]:
np.add(t1,t2)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [18]:
np.subtract(t1,t2)

array([[-10,  -9,  -8],
       [ -7,  -6,  -5],
       [ -4,  -3,  -2]])

In [19]:
np.multiply(t1,t2)

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [20]:
np.divide(t1,t2)

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8]])

In [21]:
#numpy.mod
a=np.array([10,20,30])
a

array([10, 20, 30])

In [22]:
b=np.array([3,5,7])
b

array([3, 5, 7])

In [24]:
np.mod(a,b)          #it returns remainder

array([1, 0, 2], dtype=int32)

In [25]:
a

array([10, 20, 30])

In [26]:
np.mod(a,2)

array([0, 0, 0], dtype=int32)

In [27]:
#numpy.power()
a=np.array([10,100,1000])
a

array([  10,  100, 1000])

In [28]:
b=np.array([1,2,3])
b

array([1, 2, 3])

In [29]:
np.power(a,2)

array([    100,   10000, 1000000], dtype=int32)

In [30]:
np.power(a,b)

array([        10,      10000, 1000000000], dtype=int32)

In [31]:
#numpy.reciprocal()
a=np.array([0.25,1.33,1,0,100])
a

array([  0.25,   1.33,   1.  ,   0.  , 100.  ])

In [32]:
import warnings
warnings.filterwarnings('ignore')
np.reciprocal(a)

array([4.       , 0.7518797, 1.       ,       inf, 0.01     ])

### statistical functions

In [33]:
#statistical functions
#numpy.amin,numpy.amax
#it returns min and max element from the given array
a=np.array([[3,7,5],[8,4,3],[2,4,9]])
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [34]:
np.amax(a)

9

In [35]:
np.amin(a)

2

In [36]:
np.amin(a,axis=0)

array([2, 4, 3])

In [37]:
np.amax(a,axis=0)

array([8, 7, 9])

In [38]:
np.amin(a,axis=1)

array([3, 3, 2])

In [39]:
np.amax(a,axis=1)

array([7, 8, 9])

#### whenever we are applying functions like amin,amax,mean,median,std,etc we will consider axis=0 as columns and axis 1 as rows

## numpy.ptp()

In [41]:
#numpy.ptp()
#returns range (max-min) of values along given axis
import numpy as np
a=np.array([[3,7,5],[8,4,3],[2,4,9]])
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [42]:
np.ptp(a)

7

In [43]:
np.ptp(a,axis=0)

array([6, 3, 6])

In [44]:
np.ptp(a,axis=1)

array([4, 5, 7])

In [45]:
#mean()
#sum of elements along given axis divided by number of elements
a=np.array([[1,2,3],[3,4,5],[4,5,6]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [46]:
np.mean(a)

3.6666666666666665

In [47]:
np.mean(a,axis=0)

array([2.66666667, 3.66666667, 4.66666667])

In [48]:
np.mean(a,axis=1)

array([2., 4., 5.])

### median

In [49]:
#median()
#it is defined as value seperating the higher half of a data sample from  the lower half
a=np.array([[30,65,70],[80,95,10],[50,90,60]])
a

array([[30, 65, 70],
       [80, 95, 10],
       [50, 90, 60]])

In [50]:
#10,30,50,60,65,70,80,90,95
np.median(a)

65.0

In [51]:
np.median(a,axis=0)

array([50., 90., 60.])

In [52]:
np.median(a,axis=1)

array([65., 80., 60.])

## standard deviation

In [53]:
#standard deviation
#it is a square root of avg of squared deviations from mean
#std=sqrt(mean(abs(x-xmean())**2))
import numpy as np

In [54]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [55]:
#mean of array=xmean = 2.5
#x=1,xmean=2.5 x-xmean=1-2.5=-1.5,abs(-1.5)=1.5^2=2.25
#x=2,xmean=2.5,x-xmean=2-2.5=-0.5,abs(-0.5)=0.5^2=0.25
#3-2.5=0.5^=0.25
#4-2.5=1.5^2=2.25
#sqared deviations are [2.25,0.25,0.25,2.25]
#mean(sqaured deviations) =5/4=1.25
#sqrt(1.25)=1.1180
#std=1.1180
np.std(a)


1.118033988749895

In [56]:
#variance is the measure of how far a value in the dataset lies from mean value.
#it is measured using standard deviation


In [57]:
#variance = avarage of squared deviations
np.var(a)

1.25

## numpy.argmax and numpy.argmin

In [105]:
#numpy.argmax and numpy.argmin
#it will give u the indices of min and max elements from given array
import numpy as np
a=np.array([[30,40,70],[80,20,10],[50,90,60]])
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [106]:
np.argmin(a)    #it goes like [[012]
                               #[345]
                                #[678]]

5

In [60]:
np.argmax(a)

7

In [62]:
#numpy.where
#it returns the index of elements in an array where the given condition is satishfied
x=np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
x>3

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [65]:
np.where(x>3)      #first array: rowwise 1,1,2,2,2    #second array: first it goes rowwise then it goes columnwise
                                                        #hence 1,2,0,1,2

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

## numpy.nonzero

In [66]:
#numpy.nonzero
#it returns the indices of non-zero elements in given array
a=np.array([[30,40,0],[0,20,10],[50,0,60]])
a

array([[30, 40,  0],
       [ 0, 20, 10],
       [50,  0, 60]])

In [68]:
np.nonzero(a)   #first it goes columnwise     #second it goes rowwise

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 1, 2, 0, 2], dtype=int64))

## numpy.extract

In [69]:
#numpy.extract
c=np.arange(9).reshape(3,3)
c


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
condition=np.mod(c,2)==0
condition

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [73]:
np.extract(condition,c)   #extracts actual values

array([0, 2, 4, 6, 8])

## numpy copies and view

In [74]:
#numpy copies and view
#while executing the functions ,some of them return a copy of input array ,while some return the view.when the contents are 
#physically stored in another location ,it is called a copy.If a different view of same memory content is provided ,we call it
#a view.
#no copy = simple assignments do not make a copy of array object.instead it uses the same id() of original array to access it.
#the id() returns the universal indentifier of python object

In [75]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [76]:
id(a)

2792381287472

In [77]:
b=a

In [78]:
id(b)

2792381287472

In [79]:
b

array([0, 1, 2, 3, 4, 5])

In [80]:
#change the shape of b
#b.reshape(3,2)
b.shape=(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [81]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [82]:
#view or shallow copy
#ndarray.view()
#this method creates new array object that looks same as original array .but change in dimensions of new array does not change
#the dimensions of original array
a= np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [87]:
b=a.view()    #shallow copy or view: different locations

In [84]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [85]:
id(a)

2792381334224

In [86]:
id(b)

2792381286128

In [88]:
b.shape=(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [89]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

### copy() or deep copy()

In [90]:
#copy() or deep copy()
#ndarray.copy()
#it is a complete copy of array and its objects and does not share memory with original array
a=np.array([[10,10],[2,3],[4,5]])
a

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

In [92]:
b=a.copy()           #python function

In [93]:
b

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

In [94]:
id(a)

2792381287664

In [95]:
id(b)

2792381334992

In [96]:
#change shape of b
b.shape=(2,3)
b

array([[10, 10,  2],
       [ 3,  4,  5]])

In [97]:
a

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

### numpy linear algebra

In [98]:
#numpy linear algebra
#numpy.linalg
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [99]:
#(1*4-3*2)=(4-6)=-2
np.linalg.det(a)

-2.0000000000000004

In [100]:
#numpy.matmul
a=np.array([[1,0],[0,1]])
b=np.array([[4,1],[2,2]])
a

array([[1, 0],
       [0, 1]])

In [101]:
b

array([[4, 1],
       [2, 2]])

In [102]:
np.matmul(a,b)

array([[4, 1],
       [2, 2]])

# 16-3-2022 IMPORTANT taken while teaching  pandas 

## np.vectorize()

In [2]:
#np.vectorize()
#it takes nested sequence of numpy arrays as inputs and return  a numpy array.the vectorized function evalutes normal python
#function over successive tuples .the implementation is essentially a for loop. 

def myfunc(a,b):
    if a>b:
        return a-b
    else:
        return a+b

In [4]:
print(myfunc([1,2,3,4],2))     #one list and one integer hence error

TypeError: '>' not supported between instances of 'list' and 'int'

In [6]:
import numpy as np
vfunc=np.vectorize(myfunc)
vfunc

In [7]:
print(vfunc([1,2,3,4],2))

[3 4 1 2]
